# Generated by Django 5.2.7 on 2025-11-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_food_slug_meal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(help_text='Per 100g'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='carbs_goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='daily_calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fats_goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='protein_goal',
            field=models.IntegerField(),
        ),
    ]
