# Generated by Django 5.2.7 on 2025-11-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_mealtemplate_mealtemplatefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='total_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealtemplate',
            name='total_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealtemplate',
            name='total_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealtemplate',
            name='total_protein',
            field=models.IntegerField(default=0),
        ),
    ]
