# Generated by Django 5.2.7 on 2025-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_mealtemplate_total_calories_mealtemplate_total_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtemplate',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
