# Generated by Django 5.2.7 on 2025-11-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_mealtemplate_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
