# Generated by Django 5.2.7 on 2025-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-11-04'),
            preserve_default=False,
        ),
    ]
